UPDATE SALES 
SET ORDER_NO='order_value', V_ID='v_value', C_ID='c_value', CBIZ_ID='cbiz_value', BIZ_ID='biz_value', TOT_PRICE=1000, DELIVER_DATE='2023-10-27', S_DATE='2023-10-27', WARRANTY=12, D_DATE='2024-10-26', REF='ref_value' 
WHERE SALE_ID='MJTEST2';

SELECT s.SALE_ID as SALE_ID, s.ORDER_NO as ORDER_NO, v.NAME as V_ID, c.NAME as C_ID, b1.NAME as CBIZ_ID, b2.NAME as BIZ_ID, s.TOT_PRICE as TOT_PRICE, s.DELIVER_DATE as DELIVER_DATE, s.S_DATE as S_DATE, s.WARRANTY as WARRANTY, s.D_DATE as D_DATE, s.REF as REF FROM SALES as s LEFT JOIN VENDOR AS v ON s.V_ID = v.V_ID LEFT JOIN CUSTOMER AS c ON s.C_ID = c.C_ID LEFT JOIN BUSINESS AS b1 ON s.CBIZ_ID = b1.BIZ_ID LEFT JOIN BUSINESS AS b2 ON s.BIZ_ID = b2.BIZ_ID WHERE s.SALE_ID = 'MJTEST2';

UPDATE SALES SET WARRANTY=24 WHERE SALE_ID='MJTEST2';

SELECT * FROM SALES WHERE SALE_ID='MJTEST2';

UPDATE SALES SET TOT_PRICE=10000000000 WHERE SALE_ID='MJTEST2';
